#!/bin/bash

finished=0
a=0
printf "a\ta**2\ta**3\n"
printf "=\t====\t====\n"
 
while [ $finished -eq 0 ]; do
    b=$((a**2))
    c=$((a**3))
    printf "%d\t%d\t%d\n" $a $b $c
    a=$((a+1))
    if ((a < 11)); then 

        finished=0
    else
        finished=1
    fi
done

