#!/bin/bash
### I need this script since I want to show all my docs here 
### neatly on one single pages, so that I can print the finally output page
### rather than print many files

rm -rf *.html ## rm dated html files


for file in $(ls)
do
    echo $file
    if [ -z $file ]
    then
        echo "done!"
        break
    fi
    markdown $file >$file".html"
done

## rm grabage
rm *.sh.html

## cat all html files 

for file in $(ls *.html)
do
    tag=$(echo $file|cut -d "." -f 1) ## rm the trailing ".html" in $file
    echo "<h1>"$tag"</h1>">>output.html
    cat $file >> output.html
done

echo "<h2>++++++++++ END OF FILE ++++++++++</h2>">>output.html
echo "This file is generated by <b>print.sh</b>">>output.html
echo "<i> Date: "$(date)"</i>">>output.html
mv output.html ~/Desktop/kb-vivion.html
rm *.html
